### ISSUE TITLE
Display bug in Apps screen

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eurekaclinical-user-webclient#23]
In the following case in eurekadev, the last application is lower on-screen than the others.

![screen shot 2018-05-16 at 3 54 01 pm](https://user-images.githubusercontent.com/5026087/40140692-890d8796-5921-11e8-8b03-d9b47739b6a6.png)

**Comment by mStack5522** [comment]
Which browsers do we support?
I tested on Chrome, and it works fine.

**Comment by arpost** [comment]
This is on Safari.

Chrome, Firefox, Safari, Edge and IE 10+ are what we support.

Andrew

**Comment by mStack5522** [comment]
I was testing a different css setup and tried it out on dev server, I did not make code commit, and have reset the changes. 
On a separate note, I did find a small problem in the code and fixed it, a pull request has been made.

**Comment by arpost** [comment]
Thanks!
